import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const players = sqliteTable("players", {
  id: text("id").primaryKey(),
  tour: text("tour").notNull(),
  name: text("name").notNull(),
  searchKey: text("search_key").notNull(),
  country: text("country").notNull(),
  hand: text("hand").notNull(),
  birthYear: integer("birth_year"),
  careerStart: integer("career_start").notNull(),
  careerEnd: integer("career_end").notNull(),
  rank: integer("rank"),
  rankingPoints: integer("ranking_points"),
  rating: real("rating").notNull(),
  ratingSigma: real("rating_sigma").notNull(),
  matches: integer("matches").notNull(),
  wins: integer("wins").notNull(),
  formRate: real("form_rate").notNull(),
  servePointsWon: real("serve_points_won").notNull(),
  returnPointsWon: real("return_points_won").notNull(),
  holdRate: real("hold_rate").notNull(),
  aceRate: real("ace_rate"),
  doubleFaultRate: real("double_fault_rate"),
  serveSample: integer("serve_sample").notNull(),
  returnSample: integer("return_sample").notNull(),
  hardRating: real("hard_rating").notNull(),
  hardMatches: integer("hard_matches").notNull(),
  clayRating: real("clay_rating").notNull(),
  clayMatches: integer("clay_matches").notNull(),
  grassRating: real("grass_rating").notNull(),
  grassMatches: integer("grass_matches").notNull(),
  majorTitles: integer("major_titles").notNull(),
  lastMatchDate: text("last_match_date"),
}, (table) => [
  index("idx_players_search_key").on(table.searchKey),
  index("idx_players_tour_era").on(table.tour, table.careerStart, table.careerEnd),
  index("idx_players_tour_rating").on(table.tour, table.rating),
]);
