// Generated by scripts/build_player_database.py.
export const playerDatabaseSummary = {
  "count": 7255,
  "atp": 3513,
  "wta": 3742,
  "firstYear": 1967,
  "lastYear": 2026,
  "generatedAt": "2026-08-27"
} as const;
